#!/usr/bin/env python
# -*- coding: utf-8 -*-

from engine import GeventEngine
from websites import DealMoonBox
import urllib2
import codecs
import lxml.html
import os


PAGES = 10
POOL_SIZE = 100
N_WRITERS = 6
HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'}
LOGFILE = 'ybc_cralwer.log'

def main():
    urls = ['http://cn.dealmoon.com/?sort=time&v=list&p=%d'%k for k in range(1, PAGES+1)]
    page = urllib2.urlopen('http://cn.dealmoon.com/').read()
    dFinish = 1
    dcCSS = ['div.mlist h2 a', 'div.mlist div.mbody', 'div.mlist div.mpic img']
    dnCSS = ['div.pagelink a.link']
    catURLs = []
    catDict = {}

    # create directory pages
    if not os.path.exists('pages'):
        os.makedirs('pages')

    # get lists
    dBox = DealMoonBox(0, dFinish, '', page, [dcCSS], [dnCSS,], [[],], [[],])
    categories = dBox.getCategory()
    n_category = 0
    f = codecs.open('dealmoon_category.log', 'w', encoding='utf-8')
    if not os.path.exists('cat'):
        os.makedirs('cat')
    for c in categories:
        cDOM = lxml.html.fromstring(c[0])
        f.write(str(n_category) + ': ' + cDOM.text + '\n')
        catURLs.append(cDOM.attrib['href'])
        catDict[cDOM.attrib['href']] = n_category
        if not os.path.exists('cat/%d'%n_category):
            os.makedirs('cat/%d'%n_category)
        n_category = n_category + 1
        if len(c) > 1:
            for subc in c[1:]:
                if 'dealmoon' in subc:
                    cDOM = lxml.html.fromstring(subc)
                    f.write('%d: \t%s\n'%(n_category, cDOM.text))

                    catURLs.append(cDOM.attrib['href'])
                    catDict[cDOM.attrib['href']] = n_category
                    if not os.path.exists('cat/%d'%n_category):
                        os.makedirs('cat/%d'%n_category)
                    n_category = n_category + 1
        f.write('\n')
    f.close()

    # update urls
    urls = urls + catURLs
    # start engine
    ge = GeventEngine('', LOGFILE, HEADERS, catDict, urls, POOL_SIZE, N_WRITERS)
    ge.load()
    ge.run()

if __name__ == '__main__':
    main()
